<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PublishAot>true</PublishAot>
    <TargetFramework>net9.0</TargetFramework>
    <LangVersion>13</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
    <Copyright>Copyright © Surihix 2025</Copyright>
    <FileVersion>2.0.0.0</FileVersion>
    <NativeLib>Shared</NativeLib>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>portable</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>none</DebugType>
  </PropertyGroup>
  
  <Import Project="..\NativeLogger\NativeLogger.projitems" Label="Shared"/>

</Project>
